import {chromium} from 'playwright';
import {expect} from '@playwright/test';
import fs from 'node:fs';
const base=process.env.BASE_URL||'http://localhost:3110';
const tag=base.startsWith('https')?'public':'local';
const browser=await chromium.launch({args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
const key='philosophen-install-v1',day=86400000;
const ua={ios:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1',android:'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 Chrome/130.0.0.0 Mobile Safari/537.36'};
const results=[];
async function test(name,fn){await fn();results.push(name);console.log('PASS',name)}
async function page(kind='ios',state={},width=390,standalone=false){const c=await browser.newContext({viewport:{width,height:844},...(kind==='desktop'?{}:{userAgent:ua[kind],isMobile:true,hasTouch:true}),serviceWorkers:'block'});await c.addInitScript(({key,state,standalone})=>{if(!sessionStorage.seeded){localStorage.setItem(key,JSON.stringify(state));sessionStorage.seeded='1'}if(standalone==='media'){const original=window.matchMedia.bind(window);window.matchMedia=q=>q==='(display-mode: standalone)'?{matches:true}:original(q)}else if(standalone)Object.defineProperty(navigator,'standalone',{value:true});window.addEventListener('beforeinstallprompt',e=>{if(e.isTrusted)e.stopImmediatePropagation()},true)}, {key,state,standalone});const p=await c.newPage();await p.goto(base);await expect(p.getByTestId('persona-card')).toHaveCount(8);return p}
const invite=p=>p.getByRole('dialog',{name:'Deinen Salon als App installieren?'});
async function absent(p){await p.waitForTimeout(1300);await expect(invite(p)).toHaveCount(0)}
async function overflow(p){expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await p.locator('.brand').innerText()).toBe('Armins Philosophen Kumpels.')}
try{
await test('iOS automatic invitation, exact answers, 360/390 layout, Nein survives reload',async()=>{const p=await page('ios',{},360);await expect(invite(p)).toBeVisible();await expect(invite(p).getByRole('button')).toHaveText(['Nein','Ja']);await overflow(p);await p.screenshot({path:`evidence/followup-${tag}-360-invite.png`});await p.getByRole('button',{name:'Nein',exact:true}).click();const t=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).dismissedAt,key);expect(Math.abs(Date.now()-t)).toBeLessThan(3000);await p.reload();await absent(p);await p.setViewportSize({width:390,height:844});await overflow(p);await p.screenshot({path:`evidence/followup-${tag}-390-home.png`});await p.context().close()});
await test('before expiry absent; after expiry on reload present',async()=>{const p=await page('android',{dismissedAt:Date.now()-3*day+60000});await absent(p);await p.evaluate(({key,day})=>localStorage.setItem(key,JSON.stringify({dismissedAt:Date.now()-3*day-1})),{key,day});await p.reload();await expect(invite(p)).toBeVisible();await p.context().close()});
await test('foreground expiration and Escape cooldown; manual bypass and iOS instructions',async()=>{const p=await page('ios',{dismissedAt:Date.now()});await absent(p);await p.evaluate(({key,day})=>{localStorage.setItem(key,JSON.stringify({dismissedAt:Date.now()-3*day-1}));document.dispatchEvent(new Event('visibilitychange'))},{key,day});await expect(invite(p)).toBeVisible();await p.keyboard.press('Escape');await p.reload();await absent(p);await p.getByRole('button',{name:/App installieren/}).click();await expect(p.getByRole('dialog')).toContainText('Zum Home-Bildschirm');await expect(p.getByRole('dialog')).toContainText('Teilen');await p.screenshot({path:`evidence/followup-${tag}-ios-instructions.png`});await p.context().close()});
await test('Ja iOS fallback and Android fallback',async()=>{for(const kind of ['ios','android']){const p=await page(kind);await p.getByRole('button',{name:'Ja',exact:true}).click();await expect(p.getByRole('dialog')).toContainText(kind==='ios'?'Teilen':'Browsermenü');await p.context().close()}});
await test('late saved native event consumed by Ja; cancellation cooldown; appinstalled suppression',async()=>{const p=await page('android');await expect(invite(p)).toBeVisible();await p.evaluate(()=>{const e=new Event('beforeinstallprompt',{cancelable:true});e.prompt=async()=>{window.promptCalls=(window.promptCalls||0)+1};e.userChoice=Promise.resolve({outcome:'dismissed'});window.dispatchEvent(e)});await p.getByRole('button',{name:'Ja',exact:true}).click();expect(await p.evaluate(()=>window.promptCalls)).toBe(1);await p.reload();await absent(p);await p.evaluate(()=>window.dispatchEvent(new Event('appinstalled')));await p.reload();await absent(p);await p.context().close()});
await test('standalone and desktop never automatically invited',async()=>{for(const [kind,standalone]of [['ios',true],['android','media'],['desktop',false]]){const p=await page(kind,{},390,standalone);await absent(p);if(standalone)await expect(p.getByRole('button',{name:/App installieren/})).toHaveCount(0);await p.context().close()}});
await test('other modal, chat and recording defer expiration; removed UI text absent',async()=>{const p=await page('android',{dismissedAt:Date.now()},360);const removed=['Imaginative KI-Simulationen, keine historischen Originalstimmen oder verlässlichen Zitate.','EST. HEUTE','Die großen Fragen des Lebens. Acht außergewöhnliche Perspektiven. Und ein Gespräch, das ganz bei dir beginnt.','KI-Simulation · keine Originalzitate','Ein guter Gedanke braucht manchmal einen Moment.'];async function clean(){for(const text of removed)await expect(p.locator('body')).not.toContainText(text)}await clean();await p.getByRole('button',{name:'Datenschutz & Hinweise'}).click();await p.evaluate(({key,day})=>localStorage.setItem(key,JSON.stringify({dismissedAt:Date.now()-4*day})),{key,day});await absent(p);await expect(p.getByRole('dialog')).toContainText('Groq');await expect(p.getByRole('dialog')).not.toContainText('Simulation');await p.getByRole('button',{name:'Zurück zum Salon'}).click();await p.getByTestId('persona-card').first().click();await p.getByTestId('chat-input').fill('Eine Testfrage');let release;await p.route('**/api/chat',async r=>{await new Promise(resolve=>release=resolve);await r.fulfill({json:{reply:'Eine Testantwort.'}})});await p.getByTestId('send-button').click();await absent(p);await clean();release();await expect(p.getByTestId('send-button')).toBeVisible();await p.getByTestId('mic').click();await expect(p.getByRole('button',{name:'Aufnahme stoppen',exact:true})).toBeVisible();await absent(p);await overflow(p);await p.getByRole('button',{name:'Verwerfen',exact:true}).click();await p.getByTestId('back').click();await expect(invite(p)).toBeVisible();await p.context().close()});
await test('backdrop dismissal persists cooldown',async()=>{const p=await page();await expect(invite(p)).toBeVisible();await p.mouse.click(2,2);await p.reload();await absent(p);await p.context().close()});
await test('storage denied does not crash or repeat in same page',async()=>{const p=await page('ios',{dismissedAt:Date.now()-4*day});await p.evaluate(()=>{Storage.prototype.setItem=()=>{throw Error('denied')}});await p.getByRole('button',{name:'Nein',exact:true}).click();await absent(p);await p.context().close()});
}finally{fs.writeFileSync(`evidence/followup-${tag}-results.json`,JSON.stringify({base,results,passed:results.length,at:new Date().toISOString()},null,2));await browser.close()}
