import {test} from 'node:test';import assert from 'node:assert/strict';import request from 'supertest';import {createApp} from '../server/index.js';import {SPEECH_VOICES,splitSpeech} from '../server/speech.js';
const body={version:'tts-test',philosopher:'sokrates',text:'Guten Tag, Armin.'};
const mp3=()=>new Response(Buffer.from([255,251,144,0,1,2,3,4]),{headers:{'content-type':'audio/mpeg'}});
function app(extra={}){return createApp({version:'tts-test',env:{ELEVENLABS_API_KEY:'fake'},fetch:async()=>mp3(),...extra})}
const post=(a,b=body)=>request(a).post('/api/speech').send(b);
test('all male/female voices server controlled, output headers and full text',async()=>{for(const [philosopher,voice] of Object.entries(SPEECH_VOICES)){let seen;const a=app({fetch:async(url,init)=>{seen={url,init};return mp3()}});const r=await post(a,{...body,philosopher,voice_id:'attacker'});assert.equal(r.status,200);assert.match(seen.url,new RegExp('/'+voice+'\\?'));assert.equal(JSON.parse(seen.init.body).text,body.text);assert.equal(JSON.parse(seen.init.body).language_code,'de');assert.equal(r.headers['cache-control'],'no-store');assert.equal(r.headers['x-app-version'],'tts-test')}});
test('input, version, unknown persona, content type and origin fail before provider',async()=>{let calls=0;const a=app({fetch:async()=>{calls++;return mp3()}});for(const [b,status]of [[{},400],[{...body,version:'old'},409],[{...body,philosopher:'__proto__'},400],[{...body,text:''},400],[{...body,text:3},400],[{...body,text:'a'.repeat(16001)},400],[{...body,text:'\u0000'},400]])assert.equal((await post(a,b)).status,status);assert.equal((await request(a).post('/api/speech').set('Origin','https://evil.example').send(body)).status,403);assert.equal((await request(a).post('/api/speech').set('Content-Type','text/plain').send('text')).status,415);assert.equal(calls,0)});
test('complete long outputs split without losing characters, no surrogate split',async()=>{const text=('Gedanken und Freiheit. 😀 '.repeat(650)).slice(0,16000);assert.equal(splitSpeech(text).join(''),text);assert.ok(splitSpeech(text).every(x=>x.length<=8000));let parts=[];const a=app({fetch:async(u,i)=>{parts.push(JSON.parse(i.body).text);return mp3()}});assert.equal((await post(a,{...body,text})).status,200);assert.equal(parts.join(''),text)});
test('timeout aborts fetch and slot released for retry',async()=>{let fail=true;const a=app({speechTimeoutMs:20,fetch:async(u,i)=>{if(!fail)return mp3();return new Promise((r,j)=>i.signal.addEventListener('abort',()=>j(Error('abort'))))}});assert.equal((await post(a)).status,504);fail=false;assert.equal((await post(a)).status,200)});
test('provider status, empty/type/signature/oversized errors and retry',async()=>{for(const response of [()=>new Response('oops',{status:500}),()=>new Response('',{headers:{'content-type':'audio/mpeg'}}),()=>new Response('{}',{headers:{'content-type':'application/json'}}),()=>new Response('not an mp3',{headers:{'content-type':'audio/mpeg'}}),()=>new Response(Buffer.alloc(30),{headers:{'content-type':'audio/mpeg'}})]){let fail=true;const a=app({speechMaxBytes:20,fetch:async()=>fail?response():mp3()});assert.equal((await post(a)).status,502);fail=false;assert.equal((await post(a)).status,200)}});
test('independent per-IP request, character and global character budgets',async()=>{for(const opts of [{speechPerMinute:1},{speechIpChars:body.text.length}]){const a=app(opts);assert.equal((await post(a)).status,200);assert.equal((await post(a)).status,429)}const a=app({speechGlobalChars:body.text.length});assert.equal((await post(a)).status,200);assert.equal((await post(a)).status,503);assert.equal((await request(a).get('/healthz')).status,200)});
test('concurrent request rejects before charging; disconnect aborts provider',async()=>{let entered,aborted;const ready=new Promise(r=>entered=r),done=new Promise(r=>aborted=r);const a=app({fetch:async(u,i)=>{entered();return new Promise((r,j)=>i.signal.addEventListener('abort',()=>{aborted();j(Error('abort'))}))}});const server=a.listen(0);try{const ctrl=new AbortController();const pending=fetch(`http://127.0.0.1:${server.address().port}/api/speech`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:ctrl.signal}).catch(()=>{});await ready;assert.equal((await post(a)).status,503);ctrl.abort();await done;await pending}finally{server.closeAllConnections();server.close()}});
